services:
  book-eat-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      BOT: 7619801086:AAEF0owPILwMnUPG4dOtXW_heXJD7OfSFEA
      EXTERNAL_API_URL: https://book-eat-test.ru/book-eat/api/
      EXTERNAL_API_CHECK_ACCESS: https://book-eat-test.ru/book-eat/api/v1/users/check-for-bot
    networks:
      - default_network